---
development:
  cloud_name: dssc4mht3
  api_key: '977891995729873'
  api_secret: 3AVSbkc02yVG7ewhnFTkX2vScpY
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dssc4mht3
  api_key: '977891995729873'
  api_secret: 3AVSbkc02yVG7ewhnFTkX2vScpY
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dssc4mht3
  api_key: '977891995729873'
  api_secret: 3AVSbkc02yVG7ewhnFTkX2vScpY
  enhance_image_tag: true
  static_file_support: false
